services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webring
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webring
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      API_USER: usuario
      API_PASS: senha
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONUNBUFFERED: 1
      IS_BETA: 1
      WEBRING_URL: https://nosnocabo.pages.dev
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  db_data:
