"""increase short_url length

Revision ID: 37333c3061de
Revises: 
Create Date: 2026-06-23 14:13:58.976344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37333c3061de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preWebsite')
    op.alter_column('url_analytics', 'short_url',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('url_analytics', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=0)
    op.create_unique_constraint(None, 'url_analytics', ['short_url'])
    op.alter_column('url_mappings', 'short_url',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.create_unique_constraint(None, 'url_mappings', ['short_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_mappings', type_='unique')
    op.alter_column('url_mappings', 'short_url',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'url_analytics', type_='unique')
    op.alter_column('url_analytics', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('url_analytics', 'short_url',
               existing_type=sa.String(length=11),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_table('preWebsite',
    sa.Column('url', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('createdAt', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('faviconUrl', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"preWebsite_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='preWebsite_pkey'),
    sa.UniqueConstraint('url', name='preWebsite_url_key')
    )
    # ### end Alembic commands ###
