"""recreate url tables with integer id

Revision ID: 6bfa0407a4a2
Revises: b83ec599e6a1
Create Date: 2026-06-23 16:33:39.221427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfa0407a4a2'
down_revision: Union[str, None] = 'b83ec599e6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url_analytics', ['short_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_analytics', type_='unique')
    # ### end Alembic commands ###
