"""sync database constraints

Revision ID: abc868f825eb
Revises: 37333c3061de
Create Date: 2026-06-23 14:38:38.034608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abc868f825eb'
down_revision: Union[str, None] = '37333c3061de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_analytics', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=0)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('url_analytics', 'click_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
