"""recreate url tables with integer id

Revision ID: b83ec599e6a1
Revises: abc868f825eb
Create Date: 2026-06-23 14:59:22.777951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83ec599e6a1'
down_revision: Union[str, None] = 'abc868f825eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_url', sa.String(length=11), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    op.create_table('url_analytics',
    sa.Column('short_url', sa.String(length=11), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['short_url'], ['url_mappings.short_url'], ),
    sa.PrimaryKeyConstraint('short_url'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_analytics')
    op.drop_table('url_mappings')
    # ### end Alembic commands ###
